### ISSUE TITLE
(MR/VR) Characters or models collision above the floor or furniture

### ISSUE THREAD

**Issue by Aktion** [fortellgames/bw_bugtracker#228]

**Comment by DaviveCZ** [comment]
https://github.com/user-attachments/assets/86d0efbc-ed37-4db2-a5d1-fef7e419540b

feel free to pause on some of the text if it goes too fast.

**Comment by DaviveCZ** [comment]
"btw the collision of the floor is a game problem and not how i have it set up.
If you try to clip the cube into the floor like i did in that video by making the floor disappear and then reappear with the cube in it.
you can see how height-wise the cube is correct with the real and virtual floor. but the moment you try to pick it up with the tether thing, it pops the cube above the floor. So it's a collision issue more or less than the room setup. I'm not sure how the collision is generated if it's a mesh collider or cube collider but either way it's wrong"


https://github.com/user-attachments/assets/247f1383-ac64-4401-bb5c-b64377746db5

**Comment by Aktion** [comment]
Thank you!

**Comment by dianateper** [comment]
Fixed in the latest update 2.0.0.105 (96)

**Comment by DaviveCZ** [comment]
![image](https://github.com/user-attachments/assets/b4f02962-5dca-442e-af35-a74c9e4776c7)
i don't think it's fixed. Only the virtual floor and endless expanse's ground was raised.
The room's collision itself needs to be lowered to get to real ground level.
It does fix the item poping back up tho.

**Comment by Aktion** [comment]
Lets confirm its fixed @DaviveCZ ?

**Comment by DaviveCZ** [comment]
it's much better now. it looks like it's on the floor now

**Comment by Aktion** [comment]
ok im closing now but lets keep an eye - Meta SDK is responsible for floor level
